### ISSUE TITLE
Can't paste into console anymore

### ISSUE THREAD

**Issue by myself248** [cncjs/cncjs#241] opened 2017-12-14 22:46 UTC
#### Description

In previous versions, where there was a text entry box above the console, I could copy some text from Notepad and paste it into the box, then hit enter to execute it. This was part of my single-step debugging of new g-code. 

Now that the cursor lands right in the console window, Ctrl-V doesn't seem to paste (does it get passed straight to grbl? It seems to hang the machine) and I can't right-click-paste either. While I like the feel of the interactive terminal window, feature-wise this seems like a regression.

#### Versions

- CNCjs: 1.9.12
- Node.js: 6.x?
- NPM: 5.x?

#### How Do You Install CNCjs?

- [x] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl

#### Hardware

- [x] Desktop or Laptop

#### Operating System

- [x ] Windows

**Comment by silverfoxvt** [comment] 2017-12-23 12:53
This is also an issue running CNC.js 1.9.12 on OSX High Sierra 10.13.2.  Cannot cut/copy/paste to or from any portion of the app.  Ctrl-C, Ctrl-X, Ctrl-V do not work nor is there an Edit menu in the CNC.js OSX menu bar. App completely useless for pasting large g-code code blocks to create macros or for backing up g-code settings from the CNC.js terminal.

**Comment by AustinSaintAubin** [comment] 2017-12-23 16:02
Confirmed that non of the keyboard macros work on OSX High Sierra 10.13.2. with CNC.js 1.9.12
Looks like the Mac Electron app is failing to load /api/macros and a few other.
<img width="541" alt="screen shot 2017-12-23 at 10 00 31 am" src="https://user-images.githubusercontent.com/969780/34320868-27891ed8-e7c8-11e7-9410-643e814e6cf0.png">

**Comment by cheton** [comment] 2017-12-26 08:42
This will be fixed by the pull request https://github.com/cncjs/cncjs/pull/249

**Comment by cheton** [comment] 2017-12-26 08:47
Hi @whimsycwd 
I believe you may run into the same problem with the Electron app, you can take a look at these commits and fix the copy/paste issue on your side. Thanks. 😃

**Comment by cheton** [comment] 2017-12-26 09:02
Reopen this issue until 1.9.13 is released

**Comment by cheton** [comment] 2018-01-15 16:51
New improvements to the console widget will be available in 1.9.13

![image](https://user-images.githubusercontent.com/447801/34953241-44aa1584-fa57-11e7-8803-9bffa59eef4c.png)
![image](https://user-images.githubusercontent.com/447801/34953262-53798914-fa57-11e7-8b1b-e9c3ee8f4ea2.png)

**Comment by cheton** [comment] 2018-02-03 09:36
Fixed in 1.9.13
https://github.com/cncjs/cncjs/releases/tag/v1.9.13

**Closed by cheton** 2018-02-03 09:36 UTC
Labels: Electron, bug, enhancement
