### ISSUE TITLE
Load gcode without serial connection

### ISSUE THREAD

**Issue by pchanial** [cncjs/cncjs#256] opened 2018-01-17 00:21 UTC
### Description

If I am not mistaken, it is not possible to load a gcode file before establishing a serial connection.
It would be nice to be able to visualize the gcode toolpaths without such a connection.

#### Versions

- CNCjs: 1.9.x
- Node.js: 6.x
- NPM: 5.x

#### How Do You Install CNCjs?

- [x] NPM
- [ ] Download the CNCjs Desktop Application

#### CNC Controller

- [ ] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [ ] Raspberry Pi
- [x] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [x] Not Applicable
- [ ] Windows
- [ ] Mac
- [ ] Linux

**Comment by AustinSaintAubin** [comment] 2018-01-18 00:19
One option is to use a low cost Arduino clone board and load GRBL on it.
https://m.banggood.com/ATmega328P-Nano-V3-Controller-Board-Compatible-Arduino-p-940937.html?gmcCountry=USD&currency=USD

**Comment by cheton** [comment] 2018-01-18 03:35
Duplicate of #114

**Comment by arsdragonfly** [comment] 2019-08-23 15:02
See [This GRBL simulator](https://github.com/grbl/grbl-sim)

**Comment by emcniece** [comment] 2022-03-27 20:37
Closing as duplicate!

**Closed by emcniece** 2022-03-27 20:37 UTC
Labels: 🧹 duplicate, ⭐ feature (enhancement)
