### ISSUE TITLE
Docker Tag: Latest removed. Docker no longer has latest revison

### ISSUE THREAD

**Issue by Alphacosmos** [cncjs/cncjs#752] opened 2022-03-27 20:05 UTC
#### Description

Describe the issue or feature request in detail. Take a screenshot or record a video will be helpful.

#### Versions

- CNCjs: 1.9.x
- Node.js: 6.x
- NPM: 5.x

#### How Do You Install CNCjs?

- [x] NPM
- [ ] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [x] Raspberry Pi
- [ ] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [x] Not Applicable
- [ ] Windows
- [ ] Mac
- [ ] Linux

**Comment by emcniece** [comment] 2022-03-27 20:07
Duplicate of https://github.com/cncjs/cncjs/issues/741, closing for consolidation. Thank you for the report!

**Closed by emcniece** 2022-03-27 20:07 UTC
Labels: 🧹 duplicate, install:docker
