### ISSUE TITLE
Feature Request - Auto Leveling

### ISSUE THREAD

**Issue by leoheck** [cncjs/cncjs#533] opened 2019-11-08 14:41 UTC
Hi, I was using this [OpenCNCPilot](https://github.com/martin2250/OpenCNCPilot/issues/28), it is awesome, I was thinking here, is it possible to add this functionality to the CNCjs?

**Comment by aldenhart** [comment] 2019-11-08 14:57
Note that g2core has a leveling function built in that you could use.

**Comment by leoheck** [comment] 2019-11-08 14:59
Hi @aldenhart what is g2core? do you have any extra reference?

**Comment by leoheck** [comment] 2019-11-08 15:04
I found this [What-is-g2core](https://github.com/synthetos/g2/wiki/What-is-g2core). How this is related to the CNCjs?

**Comment by leoheck** [comment] 2019-11-08 15:06
Maybe related with https://github.com/cncjs/cncjs/issues/32

**Comment by aldenhart** [comment] 2019-11-08 15:07
Yes, What is g2core is the connection. g2core is one of the CNC firmwares supported by CNCjs.

**Comment by leoheck** [comment] 2019-11-08 15:10
I am using the GRBL 1.1 firmware. Do you have any reference about how to use this kind of feature?

**Comment by ril3y** [comment] 2019-11-08 15:33
grbl is not g2core.  G2core is completely different :(

**Comment by leoheck** [comment] 2019-11-08 16:46
Oh, I see, so g2core is also a firmware like GRBL.
So, any chance to have these auto-leveling feature included on CNCjs anytime soon?
I was not able to understand if something was implemented on issue #32

**Comment by MitchBradley** [comment] 2019-11-08 17:22
This request is a duplicate of issue #32 .   Please see that for a solution to your problem.

**Closed by MitchBradley** 2019-11-08 17:22 UTC
